version: '3'
services:
  web:
    build: ./app
    command: php -S 0.0.0.0:80 -t /app
    hostname: web
    network_mode: bridge
    links:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./app:/app

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    hostname: db
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: root
      #      MYSQL_USER: root
      #MYSQL_PASSWORD: root
      MYSQL_DATABASE: registration
    ports:
      - "3306:3306"
volumes:
    db_data: